export type Permission =
  | 'DASHBOARD_VER'

  | 'VENTAS_CREAR'
  | 'VENTAS_HISTORIAL_VER'
  | 'VENTAS_DEVOLVER'
  | 'VENTAS_CANCELAR'

  | 'INVENTARIO_VER'
  | 'INVENTARIO_EDITAR'
  | 'INVENTARIO_MOVIMIENTOS_VER'

  | 'TURNOS_VER'
  | 'TURNOS_ABRIR'
  | 'TURNOS_CERRAR'

  | 'PRODUCTOS_VER'
  | 'PRODUCTOS_GESTIONAR'

  | 'USUARIOS_VER'
  | 'USUARIOS_GESTIONAR'

  | 'TIENDAS_VER'
  | 'TIENDAS_GESTIONAR'

  | 'REPORTES_VER';